networks:
  pretix:
    driver: bridge
    internal: false

services:
  # https://github.com/Soluto/oidc-server-mock
  idp-citizen:
    # image: ghcr.io/soluto/oidc-server-mock:latest
    # https://github.com/Soluto/oidc-server-mock/issues/151
    image: ghcr.io/soluto/oidc-server-mock:0.8.6
    # Let this container be accessible both internally and externally on the same domain.
    container_name: idp-citizen.${COMPOSE_SERVER_DOMAIN}
    networks:
      - app
      - frontend
    ports:
      - '80'
    volumes:
      - .:/tmp/config:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}_idp-citizen.rule=Host(`idp-citizen.${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}_idp-citizen.loadbalancer.server.port=80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_INLINE: |
        AccessTokenJwtType: JWT
        Discovery:
          ShowKeySet: true
        Authentication:
          CookieSameSiteMode: Lax
          CheckSessionCookieSameSiteMode: Lax
        KeyManagement:
          Enabled: false

      LOGIN_OPTIONS_INLINE: |
        {
          "AllowRememberLogin": false
        }

      LOGOUT_OPTIONS_INLINE: |
        {
          "AutomaticRedirectAfterSignOut": true
        }

      CLIENTS_CONFIGURATION_INLINE: |
        - ClientId: client-id
          ClientSecrets: [client-secret]
          Description: Mock IdP
          AllowedGrantTypes:
            # - client_credentials
            # - implicit
            - authorization_code
          # https://github.com/Soluto/oidc-server-mock/issues/46#issuecomment-704963181
          RequireClientSecret: false
          AllowAccessTokensViaBrowser: true
          # https://github.com/Soluto/oidc-server-mock/issues/26#issuecomment-705022941
          AlwaysIncludeUserClaimsInIdToken: true
          AllowedScopes:
            - openid
            - profile
            - email
          ClientClaimsPrefix: ''
          RedirectUris:
            - '*'
          # https://github.com/Soluto/oidc-server-mock/issues/60
          PostLogoutRedirectUris:
            - '*'
          # https://github.com/Soluto/oidc-server-mock/issues/46#issuecomment-704845375
          RequirePkce: false

      # Needed to set custom claim types in "profile"
      # https://github.com/Soluto/oidc-server-mock/issues/123#issuecomment-1427129278
      # https://github.com/Soluto/oidc-server-mock/blob/master/README.md#simple-configuration
      # https://docs.docker.com/compose/compose-file/compose-file-v3/#environment
      OVERRIDE_STANDARD_IDENTITY_RESOURCES: 'true'
      IDENTITY_RESOURCES_INLINE: |
        # https://auth0.com/docs/get-started/apis/scopes/openid-connect-scopes#standard-claims
        - Name: openid
          ClaimTypes:
            - sub
        - Name: email
          ClaimTypes:
            - email
        - Name: profile
          ClaimTypes:
            # Add your custom claims here
            - dk_ssn
            - name
            - zip

      USERS_CONFIGURATION_INLINE: |
        - SubjectId: 1
          Username: citizen1
          Password: citizen1
          Claims:
            # Claims added here must be defined above in IDENTITY_RESOURCES_INLINE
          - Type: dk_ssn
            Value: '1111111111'
            ValueType: string
          - Type: name
            Value: 'Anders And'
            ValueType: string
          - Type: zip
            Value: '1111'
            ValueType: string

        - SubjectId: 2
          Username: citizen2
          Password: citizen2
          Claims:
          - Type: dk_ssn
            Value: '2222222222'
            ValueType: string
          - Type: name
            Value: 'Bent Betjentsen'
            ValueType: string
          - Type: zip
            Value: '2222'
            ValueType: string

        - SubjectId: 3
          Username: citizen3
          Password: citizen3
          Claims:
          - Type: dk_ssn
            Value: '3333333333'
            ValueType: string
          - Type: name
            Value: 'Carsten Carlsen'
            ValueType: string
          - Type: zip
            Value: '3333'
            ValueType: string

        - SubjectId: 4
          Username: citizen4
          Password: citizen4
          Claims:
          - Type: dk_ssn
            Value: '4444444444'
            ValueType: string
          - Type: name
            Value: 'Dorte Dyhr'
            ValueType: string
          - Type: zip
            Value: '4444'
            ValueType: string

        - SubjectId: 'ikke-aarhusianer'
          Username: 'ikke-aarhusianer'
          Password: 'ikke-aarhusianer'
          Claims:
          - Type: dk_ssn
            Value: '1705880000'
            ValueType: string
          - Type: name
            Value: Troels Bondetest
            ValueType: string

        - SubjectId: 'aarhusianer'
          Username: 'aarhusianer'
          Password: 'aarhusianer'
          Claims:
          - Type: dk_ssn
            Value: '2611740000'
            ValueType: string
          - Type: name
            Value: Betina Henningsentest
            ValueType: string
